CREATE TABLE users
(
  id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) UNIQUE,
  user_id VARCHAR(30) UNIQUE NOT NULL,
	password VARCHAR(300) NOT NULL,
  creataed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);