CREATE TABLE images
(
  id INT NOT NULL AUTO_INCREMENT,
  product_id INT NOT NULL,
  image_url TEXT NOT NUll,
  creataed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);